services:
  mariadba0:
    image: mariadb
    container_name: mariadba0
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_USER: agente
      MARIADB_USER_PASSWORD: 0traClave
      MARIADB_DATABASE: ciber
    volumes:
      - mariadba0_dataa0:/var/lib/mysql
      - ./perfumes.sql://docker-entrypoint-initdb.d/perfumes.sql:ro
    user: mysql
  phpmyadmina0:
    image: phpmyadmin
    container_name: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
    ports:
      - 7000:80
    depends_on:
      - mariadba0
  pythona0:
    build: ./api
    container_name: pythona0
    environment:
      DB_USERNAME: root
      DB_PASSWORD: example
      DB_DATABASE: ciber
      DB_HOST: mariadba0
      DB_PORT: 3306
      PORT: 8080
      HOST: 0.0.0.0
    depends_on:
      - mariadba0
  apachea0:
    build: ./apache #./waf/ en un futuro
    ports:
      - 6000:80
    depends_on:
      - pythona0
    links:
      - pythona0
volumes:
  mariadba0_dataa0:
