version: "3.9"

services:
  mariadba10:
    image: mariadb
    container_name: mariadba10
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - mariadb-dataa10:/var/lib/mysql
      - ./perfumes.sql:/docker-entrypoint-initdb.d/perfumes.sql:ro

  phpmyadmina10:
    image: phpmyadmin
    container_name: phpmyadmina10
    restart: unless-stopped
    env_file:
      - .env
    environment:
      PMA_HOST: mariadba10
    ports:
      - "7010:80"
    depends_on:
      - mariadba10

  pythona10:
    build: ./api
    container_name: pythona10
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mariadba10

  apachea10:
    build: ./apache
    container_name: apachea10
    restart: unless-stopped
    ports:
      - "60010:80"
    depends_on:
      - pythona10

volumes:
  mariadb-dataa10:
